INSERT INTO code (NAME, VERSION, CREATIONTIME, UPDATETIME)
VALUES ('Cod-e', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO bins (COLOR, DTYPE , DESCRIPTION, CODE_ID, VERSION, CREATIONTIME, UPDATETIME)
VALUES ('Blue', 'BLUE_BIN','I AM A BLUE BIN AND I DO BLUE BIN THINGS', 4, 1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO items (NAME, DESCRIPTION, ENVIRONMENTALIMPACT, BIN_ID, VERSION, CREATIONTIME, UPDATETIME)
VALUES ('Caixa de chocapic', 'Eu sou uma caixa de chocapic', 5, 4, 1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO speeches( CODE_ID, DTYPE,  VERSION, CREATIONTIME, UPDATETIME)
VALUES (1, 'WELCOME', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO dialogs(TEXT, SPEECH_ID, VERSION, CREATIONTIME, UPDATETIME )
VALUES ('Eu sou uma welcome dialog', 1, 1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);